### ISSUE TITLE
Most Parts not usable until higher Tiers are unlocked!

### ISSUE THREAD

**Issue by knigh7m4r3** [mrhid6/SF_Mod_RefinedPower#10]
This is more a request for rebalancing the mod.

E.G. take the WindTurbines M.K. 2 & 3 - you unlock them in Stage 5 but you need Turbo-Motor or Aluminium-Sheet for them, which are unlocked in Stage 7/8.... so completly useless to unlock them (or place them) in Stage 5..
Could you either refine the recipes or put them in a later stage (which would be not my favorite)?

**Comment by mrhid6** [comment]
Issue fixed.
