### ISSUE TITLE
Update 4

### ISSUE THREAD

**Issue by Sherkhan-1** [mrhid6/SF_Mod_RefinedPower#103]
Any chance of this mode being updated for the new version?

**Comment by trunkyredstone** [comment]
Yeah I'm working on it. I'll leave the issue open for now so people can see it

**Comment by Sherkhan-1** [comment]
Awesome, very glad to hear that.

**Comment by ducksnero** [comment]
When do you expect the completion ?

**Comment by mrhid6** [comment]
> When do you expect the completion ?

RP is still in development please be patient

**Comment by x10an14** [comment]
Mind if I ask for another update? Also curious as to the bug =)

**Comment by trunkyredstone** [comment]
Released a while back, closing now
