### ISSUE TITLE
E65's world texture is broken

### ISSUE THREAD

**Issue by TheVekter** [mrhid6/SF_Mod_RefinedPower#104]
![image](https://user-images.githubusercontent.com/7019927/125155693-3c811a00-e127-11eb-8cce-475aa14e9e0e.png)

Not sure what would be conflicting with it if it's a mod conflict but it definitely isn't showing up correctly for me.

Here's my mod list:
![image](https://user-images.githubusercontent.com/7019927/125155714-5c184280-e127-11eb-9095-66ffe83c5429.png)

E: This appears to only happen on belts, as I can drop it in the world and it shows up fine.

**Comment by ravenhawk9999** [comment]
This is a known issue common to all of the added materials in RP. FF may also have the same issue when it's update to U4 is complete. The modders decided that U4 compatibility was more important than eye candy.

**Comment by TheVekter** [comment]
It's all good, I just didn't see it in the known issues list on the Discord. Just wanted to make sure someone was aware.

**Comment by ravenhawk9999** [comment]
I don't think it's been raised specifically for E65, but it had been noticed with Coal Dust and that's when they discovered it is something with the Experimental Conveyor something or other. What I gather is the conveyor system is using different textures to reduce the load on the graphics engine.

**Comment by TheVekter** [comment]
I can confirm that, disabling Experimental Conveyor Item Rendering fixes the issue.
