### ISSUE TITLE
Request: Modular Power Generation and Carbon Refining HUB upgrades to not be gated behind Refined Power Mk2 HUB upgrade

### ISSUE THREAD

**Issue by ronpotter99** [mrhid6/SF_Mod_RefinedPower#106]
Currently (version 3.0.1), the Modular Power Generation HUB upgrade is gated behind the Refined Power Mk2 HUB upgrade. However, the Refined Power Mk2 HUB upgrade enables water and solar power generation, which is not a logical or readily apparent pre-requisite to the Modular Power Biomass or Coal heaters, or for the Carbon Refining upgrade.

It is common for non-modded Satisfactory players to rush to Coal power as a sustainable power system. Even though the need to rush Coal for consistent power is largely negated by the Refined Power mod, some players like myself really enjoy setting up larger Modular Power power plants, and want to try to rush building one without needing water or solar power pre-requisites.

My request is to unlock the Modular Power Generation and Carbon Refining HUB upgrades to be available in Tier 3 without the need for Refined Power Mk2 to be unlocked. If a tiered upgrade system is still wanted, a different suggestion would be to gate the two HUB upgrades behind the Coal Power HUB upgrade instead.

**Comment by mrhid6** [comment]
resolved.
