### ISSUE TITLE
Water-Generator doesn't get affected by nearby Water-Generators

### ISSUE THREAD

**Issue by knigh7m4r3** [mrhid6/SF_Mod_RefinedPower#11]
I think the feature from the Wind-Generator is missing right here.
i can simply build them all over my sea and get gigawatts of electricity - would it be possible to fix that?

**Comment by shengjie** [comment]
or may be limit Water-Generators to built only near water cascades

**Comment by mrhid6** [comment]
@knigh7m4r3 @shengjie  please have a look at this https://discordapp.com/channels/555424930502541343/623891487683510323/717819316959182958
