### ISSUE TITLE
ModularUI is hidden, preventing installation.

### ISSUE THREAD

**Issue by Pantheris2019** [mrhid6/SF_Mod_RefinedPower#118]
Refined power will now not work as ModularUI is hidden and is stated as a dependency of Refined Power, resulting in Mod Manager not finding the dependency and not installing ModularUI, making installation of the mod impossible.

**Comment by Rohaq** [comment]
Is there a workaround for this? Can ModularUI be installed manually?

**Comment by Imachicken29** [comment]
no the mod doesn't work rn but should be in a few hours.
