### ISSUE TITLE
Wind turbine height irrelevant?

### ISSUE THREAD

**Issue by gwilku** [mrhid6/SF_Mod_RefinedPower#13]
I started in the grasslands and expanded my base to the south, found a coal node on top of a rock formation, well above the ground level, and placed a wind turbine there -it is one of the highest points around, yet still the power produced from the turbine is 10MW. What is considered a "greater height" then?

According to the https://satisfactory-calculator.com/, the base of my turbine is at 30m (absolute).

**Comment by kjackey1** [comment]
Not sure how high they are, but I was only able to get max wattage from the
top of the pillars in the NW dunes desert area

**Comment by gwilku** [comment]
Thank you - that explains the behaviour. It would be awesome to have an actual wind value, maybe, sometime in the future if this is even implemented in the game...

**Comment by mrhid6** [comment]
The height is calculated anything above Z:8000 you can find the position out by opening the console using Shift+Ctrl+L and use the ` key and type ShowDebug.
