### ISSUE TITLE
Wind turbine MW output & elevation / clearance isnt making sense. 

### ISSUE THREAD

**Issue by Eagle-Studios** [mrhid6/SF_Mod_RefinedPower#133]
Difference in clearance and/or elevation doesnt make much sense. 
[Bug?](https://youtu.be/BS_jEfVfDg0)
Link is a video, with shows the issue.

**Comment by Imachicken29** [comment]
the elevation gives it a maximum output. the random power out is something experimental that we are tweaking

**Comment by Eagle-Studios** [comment]
But the lower elevation one was producing 8mw where as the higher one was producing 1mw....

**Comment by kulcris** [comment]
that could be based on wind speed @Eagle-Studios look at the "max output"

**Comment by Kyri123** [comment]
Maybe the wind speed was changed while u go to the point so it looks like it’s different the Wind Speed changed every 2 minutes

**Comment by Eagle-Studios** [comment]
Not sure about that... tried it several times at different times over the course of 2 hours. 
Same issue. The higher elevation had 0-1mw.
