### ISSUE TITLE
[1.3.5] Crash on startup after todays todays hotfix

### ISSUE THREAD

**Issue by Vexllith** [mrhid6/SF_Mod_RefinedPower#137]
This is the log, Game opens without the mod

Version: 174506, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: -, IsUsingMods: Yes

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffec5ab130

VCRUNTIME140
FactoryGame_CoreUObject_Win64_Shipping!FArrayProperty::CopyValuesInternal() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\propertyarray.cpp:618]
FactoryGame_CoreUObject_Win64_Shipping!FObjectInitializer::InitProperties() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:3031]
FactoryGame_CoreUObject_Win64_Shipping!FObjectInitializer::PostConstructInit() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:2794]
FactoryGame_CoreUObject_Win64_Shipping!FObjectInitializer::~FObjectInitializer() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:2706]
FactoryGame_CoreUObject_Win64_Shipping!UClass::CreateDefaultObject() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:3708]
FactoryGame_CoreUObject_Win64_Shipping!UClass::Serialize() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:4550]
FactoryGame_Engine_Win64_Shipping!UBlueprintGeneratedClass::Serialize() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\engine\private\blueprintgeneratedclass.cpp:1725]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncPackage::EventDrivenSerializeExport() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:3198]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncPackage::ProcessImportsAndExports_Event() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:3523]
FactoryGame_CoreUObject_Win64_Shipping!<lambda_021cf6e1d064bc3759a30032930b9dad>::operator()() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:2291]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncLoadingThread::ProcessAsyncLoading() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4055]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncLoadingThread::TickAsyncThread() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4840]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncLoadingThread::Run() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4767]
FactoryGame_Core_Win64_Shipping!FRunnableThreadWin::Run() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:86]

**Comment by mrhid6** [comment]
Game got updated need to update the mod, Patch will come soon.
