### ISSUE TITLE
Multiple icons in tier 3

### ISSUE THREAD

**Issue by gwilku** [mrhid6/SF_Mod_RefinedPower#14]
I noticed one more issue with this mod:
In the HUB menu, on Tier 3 I have 6 icons for Refined Power, all of them with the same reward and requirements: (water turbine mk I, photovoltaic cells, for 200 steel pipes, 1000 wire and 50 steel beams).

I haven't unlocked it yet, so I don't know if it unlocks all 6 icons, or if they stay there forever.

And also: the mod itself is great. I love the wind turbine (it's very similar to adv. turbine from Cities: Skylines)

**Comment by mrhid6** [comment]
This is a SML Bug please download SML 2.1.2

**Comment by gwilku** [comment]
I am using SML 2.1.2. After unlocking the mielstone all six icons are marked as unlocked, but still exist.
Shall I try a new session? Mod re-install? Would you like me to provide any logs/ savegames, etc?

**Comment by mrhid6** [comment]
This is because it is in the save file should be fixed in a new save.
