### ISSUE TITLE
[Bug] RefinedPower Cause Game Crash on Early Access Branch

### ISSUE THREAD

**Issue by P17seongbin** [mrhid6/SF_Mod_RefinedPower#140]
First of all, Thanks for making this mod!  

Issue: Game Crashes just after launch Satisfactory
(No Satisfactory nor Coffee Stain logo are appeared before crash)

below texts are some information that might be helpful for debuging. If further information is needed, please mention me!

Satisfactory Version: Early Access (Steam) - CL174686 (according to SML)
SML Version: SML v3.2.1
Mod Version: 3.0.5

OS Version: Win 10 21H2
Graphics API: DirectX 12

Crash log generated by UE4 crash reporter:
~~~
Version: 174686, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: -, IsUsingMods: Yes

Assertion failed: Count>=0 [File:D:\ws\SB-211116092526-440\UE4\Engine\Source\Runtime\CoreUObject\Public\UObject/UnrealType.h] [Line: 3227]

FactoryGame_Core_Win64_Shipping!AssertFailedImplV() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:104]
FactoryGame_Core_Win64_Shipping!FDebug::CheckVerifyFailedImpl() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:461]
FactoryGame_CoreUObject_Win64_Shipping!FArrayProperty::CopyValuesInternal() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\propertyarray.cpp:602]
FactoryGame_CoreUObject_Win64_Shipping!FObjectInitializer::InitProperties() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:3031]
FactoryGame_CoreUObject_Win64_Shipping!FObjectInitializer::PostConstructInit() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:2794]
FactoryGame_CoreUObject_Win64_Shipping!FObjectInitializer::~FObjectInitializer() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:2706]
FactoryGame_CoreUObject_Win64_Shipping!UClass::CreateDefaultObject() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:3708]
FactoryGame_CoreUObject_Win64_Shipping!UClass::Serialize() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:4550]
FactoryGame_Engine_Win64_Shipping!UBlueprintGeneratedClass::Serialize() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\engine\private\blueprintgeneratedclass.cpp:1725]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncPackage::EventDrivenSerializeExport() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:3198]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncPackage::ProcessImportsAndExports_Event() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:3523]
FactoryGame_CoreUObject_Win64_Shipping!<lambda_021cf6e1d064bc3759a30032930b9dad>::operator()() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:2291]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncLoadingThread::ProcessAsyncLoading() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4055]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncLoadingThread::TickAsyncThread() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4840]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncLoadingThread::Run() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4767]
FactoryGame_Core_Win64_Shipping!FRunnableThreadWin::Run() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:86]
~~~

**Comment by gman12f** [comment]
i have a similar proplem with this error message

Version: 174686, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: -, IsUsingMods: Yes

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffc88ab130

VCRUNTIME140
FactoryGame_CoreUObject_Win64_Shipping!FArrayProperty::CopyValuesInternal() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\propertyarray.cpp:618]
FactoryGame_CoreUObject_Win64_Shipping!FObjectInitializer::InitProperties() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:3031]
FactoryGame_CoreUObject_Win64_Shipping!FObjectInitializer::PostConstructInit() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:2794]
FactoryGame_CoreUObject_Win64_Shipping!FObjectInitializer::~FObjectInitializer() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:2706]
FactoryGame_CoreUObject_Win64_Shipping!UClass::CreateDefaultObject() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:3708]
FactoryGame_CoreUObject_Win64_Shipping!UClass::Serialize() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:4550]
FactoryGame_Engine_Win64_Shipping!UBlueprintGeneratedClass::Serialize() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\engine\private\blueprintgeneratedclass.cpp:1725]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncPackage::EventDrivenSerializeExport() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:3198]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncPackage::ProcessImportsAndExports_Event() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:3523]
FactoryGame_CoreUObject_Win64_Shipping!<lambda_021cf6e1d064bc3759a30032930b9dad>::operator()() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:2291]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncLoadingThread::ProcessAsyncLoading() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4055]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncLoadingThread::TickAsyncThread() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4840]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncLoadingThread::Run() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4767]
FactoryGame_Core_Win64_Shipping!FRunnableThreadWin::Run() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:86]

**Comment by Pantheris2019** [comment]
Yeah my computer makes same errors.

```
Version: 174686, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: -, IsUsingMods: Yes

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffff8482b130

VCRUNTIME140
FactoryGame_CoreUObject_Win64_Shipping!FArrayProperty::CopyValuesInternal() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\propertyarray.cpp:618]
FactoryGame_CoreUObject_Win64_Shipping!FObjectInitializer::InitProperties() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:3031]
FactoryGame_CoreUObject_Win64_Shipping!FObjectInitializer::PostConstructInit() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:2794]
FactoryGame_CoreUObject_Win64_Shipping!FObjectInitializer::~FObjectInitializer() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:2706]
FactoryGame_CoreUObject_Win64_Shipping!UClass::CreateDefaultObject() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:3708]
FactoryGame_CoreUObject_Win64_Shipping!UClass::Serialize() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:4550]
FactoryGame_Engine_Win64_Shipping!UBlueprintGeneratedClass::Serialize() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\engine\private\blueprintgeneratedclass.cpp:1725]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncPackage::EventDrivenSerializeExport() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:3198]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncPackage::ProcessImportsAndExports_Event() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:3523]
FactoryGame_CoreUObject_Win64_Shipping!<lambda_021cf6e1d064bc3759a30032930b9dad>::operator()() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:2291]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncLoadingThread::ProcessAsyncLoading() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4055]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncLoadingThread::TickAsyncThread() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4840]
FactoryGame_CoreUObject_Win64_Shipping!FAsyncLoadingThread::Run() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4767]
FactoryGame_Core_Win64_Shipping!FRunnableThreadWin::Run() [d:\ws\sb-211116092526-440\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:86]
```
