### ISSUE TITLE
Boiler MK2 doesnt show consumption or production rates

### ISSUE THREAD

**Issue by clonk2u** [mrhid6/SF_Mod_RefinedPower#148]
![image](https://user-images.githubusercontent.com/8469113/146496445-ce7272c2-00c8-4e1e-addd-39e9c78df93e.png)
Item is placed on top of a coal heater, connected to a Turbine mk 2 and directly to a vanilla water extractor. There are no pumps in the system. Only tested in multiplayer(client)

**Comment by mrhid6** [comment]
Hi @clonk2u, this looks like a replication issue does the host see those values?

**Comment by clonk2u** [comment]
Could be due to some networking bugs that got fixed in the latest update, will retest in about an hour to be sureOn Dec 17, 2021 9:01 AM, mrhid6 ***@***.***> wrote:
Hi @clonk2u, this looks like a replication issue does the host see those values?

**Comment by clonk2u** [comment]
Host can see the values.

**Comment by Kyri123** [comment]
We can close that. Is already fixed
