### ISSUE TITLE
 Feedback/Suggestion

### ISSUE THREAD

**Issue by mrvice** [mrhid6/SF_Mod_RefinedPower#15]
windturbine space is 6 empty foundations not 12 ( i personaly like the 6 you really need a lot of space 12 would be kind of insane)
I started a new game in update 3 and if i would not have Wind Turbines or needed to spread them more i would get annoyed as coal is kind of a pain since update 3. (specialy when  you have no water source nearby)
---
Windturbines always show the can output 30MW when you look at them even the MK1 ( in fact they can only output 10MW)
---
Waterturbines show proximity in their UI i dont know if it would be nicer to be able to just place them near together as the game does the same with their waterpumps. ( i did not uses the modded ones yet)

**Comment by mrhid6** [comment]
Windturbine Mk1 can output 30MW at greater heights.

Wind Turbines have now been balanced.
