### ISSUE TITLE
Disassembling Solar Panel Mk 2 Crashes Game

### ISSUE THREAD

**Issue by Malkierian** [mrhid6/SF_Mod_RefinedPower#16]
Not exactly sure what all information you're wanting, so let me know and I'll try to get it to you, but I just unlocked the Refined Power Mk 3 milestone, thus unlocking the solar panels, and I went to disassemble it (because I wanted to check power provided; there's no information on that, btw). If this was an initial WIP commit, then I won't worry about it, just wanted to let you know.

**Comment by mrhid6** [comment]
solar panels are WIP
