### ISSUE TITLE
UE Crash in new Experimental Build

### ISSUE THREAD

**Issue by gwilku** [mrhid6/SF_Mod_RefinedPower#17]
Hi,

Today a new update was rolled out: Patch Notes: Early Access (EXPERIMENTAL) - v0.3.4.11 - Build 122801, and after the patch the game doesn't launch with RefinedPower 2.0.5.
UE crashlog: https://pastebin.com/aYRpj8S9
Pre-launch debug:  https://pastebin.com/FQkKcWUx
SML Log contains only INFO entries and one warning:
[WARN] Detected game version newer than one SML was built for. Things can break or work in unexpected way. Proceed with caution.

**Comment by XxUnkn0wnxX** [comment]
ya this crashes for me as well.. 
also @gwilku consider using https://gist.github.com/ for posting logs, more convenient that way ;)

**Comment by rcamarda390** [comment]
Ditto. Sucks that I had to remove, and all construction with it.

**Comment by mrhid6** [comment]
Fixed, version will be out sometime today.

**Comment by rcamarda390** [comment]
Thanks! 👏

**Comment by mrhid6** [comment]
Version is now live https://ficsit.app/mod/DGiLzB3ZErWu2V/version/9rKCvRenmN1u7K/view
