### ISSUE TITLE
Dyson Sphere Hanger 2 not showing up to unlock

### ISSUE THREAD

**Issue by FTLNewsFeed** [mrhid6/SF_Mod_RefinedPower#18]
Since the fix under Tier 7 I can see the ability to unlock Dyson Sphere H1, H3 & H4 milestones, but for some reason H2 is not showing up for me to be able to unlock it and activate it.

**Comment by mrhid6** [comment]
ok fixed please try not to save your game or it will put multiple of that h2 milestone in the hub once you unlock dyson sphere h1. will get a patch out tonight.
