### ISSUE TITLE
Turbines Proximity

### ISSUE THREAD

**Issue by ColdBeat** [mrhid6/SF_Mod_RefinedPower#188]
It doesn't detect the amount of turbines or change the energy output if there is 2 or more turbines together. (it shutdowns on the 4th)
Line 1
![image](https://user-images.githubusercontent.com/34623684/161630336-23fac159-800c-4c23-873a-2c3240d650f3.png)
Line 2
![image](https://user-images.githubusercontent.com/34623684/161630353-e926c6c2-642d-427c-8d05-c2f2fb731551.png)
Lines setup
![image](https://user-images.githubusercontent.com/34623684/161630363-9919cd53-6311-4dde-8320-78cf648736c4.png)

**Comment by MadCat256** [comment]
![unknown](https://user-images.githubusercontent.com/103010441/161658998-60155d77-b589-406a-b3c4-225482b0d62c.png)
Confirmed the bug in my game. I placed 1 turbine and connected it to a grid. You can see the graph maintains a nice smooth power curve as extra turbines are placed next to it, then crashes suddenly to zero when the fourth is placed.

**Comment by Ruskebusk** [comment]
I think it should be like that.. at least according to this: https://docs.ficsit.app/refinedrd/latest/rp/buildings/windturbines/index.html

**Comment by mrhid6** [comment]
Fixed - Beta4
