### ISSUE TITLE
[RP v2.0.8; SF-EA 123631] Mk.1 Wind Turbine origin off-centered.

### ISSUE THREAD

**Issue by yesod-github** [mrhid6/SF_Mod_RefinedPower#19]
Mk.1 Wind Turbine origin off-centered. This affects rotation alignment. Possible affects proximity checks.

![urU1a3yK2E](https://user-images.githubusercontent.com/26621448/83541180-4c134580-a4c7-11ea-97bf-5edd6d53c2f7.gif)

P.S. Love the new mesh!

**Comment by mrhid6** [comment]
This is now fixed, Mesh was off center not the actual actor so wont effect proximity.
