### ISSUE TITLE
Request: Configuration file

### ISSUE THREAD

**Issue by makotech222** [mrhid6/SF_Mod_RefinedPower#2]
Quick Request: I'd like to see a configuration file for this mod, allowing changing power production levels, windmill distance, etc.

Thanks!

**Comment by mrhid6** [comment]
I think as this mod provides free power I feel this configuration file could be abused and seam cheaty and over powered

**Comment by dudeofawesome** [comment]
I'd really like to see a way to either decrease the power output of things like the mk1 wind turbines or increase the cost of them. As it is, they seem really unbalanced compared to the other power sources in the base game.
