### ISSUE TITLE
Feedback/Suggestion Solar Panel Mk2

### ISSUE THREAD

**Issue by koza1258** [mrhid6/SF_Mod_RefinedPower#20]
I think this is a very nice element in the game. But personally I think it is a bit unbalanced.

- Production costs should be higher than 2 to 12 batteries (from this I noticed it is so much the model) or more. I like challenges in the final stages of the game. And a little more photonic cells. I believe that the costs should be high so that all the energy obtained is balanced. As with "Wind Turbine Mk3" they are very expensive and in my opinion it is very good.

- Another thing is the difference in electricity production during the day and night. I don't know if it is intended or is it a bug? But at the worst moment it is only 10% of the maximum production. I made the screen below with the help of "perma day" mod day accelerated by 200x.

If this is not a bug, then you could use more buildings? That would use all the energy that is not used and give it away at night. Such biggggg batteries. I don't have ideas how it would work :)
But I really don't want to build x10 times more buildings to reach the goal of minimum production at night. Besides, night is my favorite time in the game: p

Besides, I really like this mod. I hope more such modifications in the game :) They really introduce a lot of variety and possibilities in the production of electricity.

![power](https://user-images.githubusercontent.com/18580612/83777688-fe930600-a689-11ea-9b8d-4a7be691e4e9.jpg)

**Comment by trunkyredstone** [comment]
Thanks for the suggestion. I do not believe that this power generation is a bug however. Solar panels have specific requirements

**Comment by trunkyredstone** [comment]
Closed. Please join our discord for further suggestions: https://discord.gg/GKePtAH
