### ISSUE TITLE
Micro Reactor has the same cost as Arc Reactor

### ISSUE THREAD

**Issue by Krzeszny** [mrhid6/SF_Mod_RefinedPower#200]
Both the Arc Reactor and the Micro Reactor cost 80 Alclad Aluminum Sheets, 40 Supercomputers and 60 AI limiters even though there's a huge difference between their sizes, 
Compare them with the vanilla Nuclear Powerplant:
![9GjPa2h4cB](https://user-images.githubusercontent.com/10529134/189190570-c26f096a-b88b-4aeb-86ee-f850a3a7fac4.png)
![FXCWR1U9LB](https://user-images.githubusercontent.com/10529134/189191392-2fde9bf1-4523-4bea-94d8-6998c997b8cc.png)
![qY3iK5rla7](https://user-images.githubusercontent.com/10529134/189191372-6a080603-4ba2-4c04-8270-b6d5fe2a568e.png)
![3EUbwa5TE5](https://user-images.githubusercontent.com/10529134/189192229-5076d53d-0ef9-49e2-9806-d83e3b3fe72e.png)

An Arc Reactor's cost mostly makes sense when compared to a Nuclear Powerplant (though it's bigger and yet requires less sheets), but a Micro Reactor is too tiny to fit such a huge amount of materials inside.

**Comment by mrhid6** [comment]
Fixed in latest build:
v3.1.0
