### ISSUE TITLE
Nuclear Heater is too weak compared to Coal/Solution Heaters

### ISSUE THREAD

**Issue by Krzeszny** [mrhid6/SF_Mod_RefinedPower#201]
I'm using the new balance values Kyrium mentioned: Nuclear Heaters consume 1/3rd fuel rods and produce 1/3rd waste compared to Nuclear Power Plants at 100% clock speed.

- Nuclear heaters produce barely 16.7% more power than Solution Heaters
- Nuclear Heaters produce only 33% more power than Coal Heaters
- It doesn't make sense to use Nuclear Heaters over other heaters because of the time and space required to build huge setups and their factories.

To see how SF is balanced, let's compare vanilla power plants OC'd to 250%:

1 Coal Generator produces 150 MW
1 Fuel Generator produces 300 MW, 2x more
1 Nuclear Power Plant produces **5000 MW**, 33x more than coal, 12.5x more than fuel

In the meanwhile:
1 Coal Heater produces up to 120 steam converted into 750 MW
1 Solution Heater produces up to 140 steam converted into 875 MW
1 Nuclear Heater produces up to 160 steam converted into 1000 MW

**Comment by Krzeszny** [comment]
To see how SF is balanced, let's compare vanilla power plants OC'd to 250%:

1 Coal Generator produces 150 MW
1 Fuel Generator produces 300 MW
1 Nuclear Power Plant produces **5000 MW**

In the meanwhile:
1 Coal Heater produces 120 steam
1 Solution Heater produces 140 steam
1 Nuclear Heater produces 160 steam
???

**Comment by Kyri123** [comment]
We rebalance the MP in the latest Beta now. You can test them if you want. The rates and informations will be updated later in the docs.
