### ISSUE TITLE
Fuel Heater is too weak compared to Coal Heater

### ISSUE THREAD

**Issue by Krzeszny** [mrhid6/SF_Mod_RefinedPower#202]
- vanilla Fuel Generators produce 100% more power than vanilla Coal Generators
- Solution Heaters produce only 16.7% more power than Coal Heaters (seriously!)

**Comment by mrhid6** [comment]
**Low priority**
Complexities between the Heaters and Boilers create a challenge for fluid output rates and compatibility between other heaters in Modular Power.

**Comment by Kyri123** [comment]
We rebalance the MP in the latest Beta now. You can test them if you want. The rates and informations will be updated later in the docs.
