### ISSUE TITLE
Modular Power resource efficiency over Vanilla

### ISSUE THREAD

**Issue by Krzeszny** [mrhid6/SF_Mod_RefinedPower#203]
Modular Power seems OP in terms of resource efficiency.
### Examples
- On the high end, burning fabric in a Mk.2 Biomass Heater setup gives you 50x more energy than burning it in a vanilla Biomass Burner (cell E6 in the spreadsheet.)
- On the low end, a post-buff Nuclear Heater gives you only 1.2x more energy than a Nuclear Power Plant (cell E19 and E20)
- On the mid end, burning coal in a Coal Heater gives you 10x more energy than burning it in a Coal Generator (cell E13.)

![vivaldi_PcAixQc1PM](https://user-images.githubusercontent.com/10529134/189502045-8c1048e5-ca06-481a-9e43-549ef6db2c15.png)

https://docs.google.com/spreadsheets/d/1UZOlCyjQTyCnpZlZHmZllOmA5-85HMHAPB7KlR0vC7I/edit#gid=0

### Proposed solution
After some thinking, the best solution I could come up with is not using whatever seems OP. You can close this issue, if you wish.

**Comment by mrhid6** [comment]
No recommended solution, not a bug or suggestion..
