### ISSUE TITLE
Water Turbine shows clearance and range, Wind Turbine doesn't

### ISSUE THREAD

**Issue by Krzeszny** [mrhid6/SF_Mod_RefinedPower#205]
Clearance?
![FactoryGame-Win64-Shipping_Ey1087gTCj](https://user-images.githubusercontent.com/10529134/190874792-88c5ba97-a4f8-445a-87d1-09b8d06770d5.png)
No clearance?
![FactoryGame-Win64-Shipping_1xb51vaIlA](https://user-images.githubusercontent.com/10529134/190874879-936cf6a7-24d8-4446-bb4b-99e50a4ebdc0.png)

**Comment by Kyri123** [comment]
Fix: we removed the clearance text

**Comment by Krzeszny** [comment]
> Fix: we removed the clearance text

btw, isn't the clearance supposed to be shown on wind turbines?

**Comment by Kyri123** [comment]
> > Fix: we removed the clearance text
> 
> btw, isn't the clearance supposed to be shown on wind turbines?

no since we have it in the build mode etc. also is the UI not designed for that
