### ISSUE TITLE
[Visual] Heaters have red hot textures by default

### ISSUE THREAD

**Issue by Krzeszny** [mrhid6/SF_Mod_RefinedPower#206]
![FactoryGame-Win64-Shipping_g1VkPsHlZ9](https://user-images.githubusercontent.com/10529134/190874980-0c6547da-5263-4ab6-9db7-627d59723b60.png)

**Comment by Krzeszny** [comment]
![FactoryGame-Win64-Shipping_g1VkPsHlZ9](https://user-images.githubusercontent.com/10529134/190874977-c03a3186-cdb4-4ecc-bbf1-63895c9e2d02.png)

**Comment by mrhid6** [comment]
Not an issue, The games furnace & forge both have emissive materials when not running.

**Comment by Krzeszny** [comment]
true
