### ISSUE TITLE
Wind Turbine Build Sphere doesn't ignore different turbine models

### ISSUE THREAD

**Issue by Krzeszny** [mrhid6/SF_Mod_RefinedPower#207]
For instance, placing a Mk.1 next to a Mk.3 makes the build sphere turn red, but it has no impact on efficiency.

If the lack of impact on efficiency _isn't_ intentional then it's a completely different bug, and the sphere works correctly but efficiency doesn't.

![FactoryGame-Win64-Shipping_cGJYfQZ5FH](https://user-images.githubusercontent.com/10529134/190875600-a0df547e-107b-4b67-b0a4-576c03a4d4e5.jpg)

**Comment by Kyri123** [comment]
Will be fixed in beta 4
