### ISSUE TITLE
Dyson Sphere crash game

### ISSUE THREAD

**Issue by except134** [mrhid6/SF_Mod_RefinedPower#22]
Then I try to choose Dyson Sphere for the build, game crash.
![error_refined_power](https://user-images.githubusercontent.com/3720359/83948420-d0e2c400-a825-11ea-9bae-eab20286ee7c.PNG)

**Comment by mrhid6** [comment]
please read this we are aware of the issue https://discordapp.com/channels/555424930502541343/555782140533407764/718148985231114311
