### ISSUE TITLE
Game crashes when selecting water turbine

### ISSUE THREAD

**Issue by fleXXo22** [mrhid6/SF_Mod_RefinedPower#23]
My game crashes, when i click on the buildmenu. I am on version 2.0.8 and on Early Access. What can i do?

My crashlog:

Version: 124066, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Epic, NetMode: Listen Server, IsUsingMods: Yes

Assertion failed: Child->IsChildOf(Parent) [File:D:\ws\SB-200518130817-657\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectGlobals.cpp] [Line: 3037] NewObject called with invalid class, SceneComponent must be a child of MeshComponent

FactoryGame_Win64_Shipping!FWindowsErrorOutputDevice::Serialize() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\windows\windowserroroutputdevice.cpp:79]
FactoryGame_Win64_Shipping!FOutputDevice::LogfImpl() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\outputdevice.cpp:71]
FactoryGame_Win64_Shipping!AssertFailedImplV() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:101]
FactoryGame_Win64_Shipping!FDebug::CheckVerifyFailedImpl() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:439]
FactoryGame_Win64_Shipping!DispatchCheckVerify<void,<lambda_bf25ddeef6581ff98ae1fa748b1445c9> >() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\public\misc\assertionmacros.h:161]
FactoryGame_Win64_Shipping!CheckIsClassChildOf_Internal() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\uobjectglobals.cpp:3037]
FactoryGame_Win64_Shipping!AFGHologram::SetupDepthMeshComponent() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\hologram\fghologram.cpp:347]
FactoryGame_Win64_Shipping!FGComponentHelpers::DuplicateComponents() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\fgcomponenthelpers.cpp:40]
FactoryGame_Win64_Shipping!AFGHologram::BeginPlay() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\hologram\fghologram.cpp:172]
UE4_RefinedPower_Win64_Shipping
FactoryGame_Win64_Shipping!AActor::DispatchBeginPlay() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\actor.cpp:3395]
FactoryGame_Win64_Shipping!AActor::PostActorConstruction() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\actor.cpp:3256]
FactoryGame_Win64_Shipping!AActor::FinishSpawning() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\actor.cpp:3152]
FactoryGame_Win64_Shipping!AFGHologram::SpawnHologramFromRecipe() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\hologram\fghologram.cpp:114]
FactoryGame_Win64_Shipping!UFGBuildGunStateBuild::InternalSpawnHologram() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\equipment\fgbuildgunbuild.cpp:1196]
FactoryGame_Win64_Shipping!UFGBuildGunStateBuild::SpawnHologram() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\equipment\fgbuildgunbuild.cpp:866]
FactoryGame_Win64_Shipping!UFGBuildGunStateBuild::SetActiveRecipe() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\equipment\fgbuildgunbuild.cpp:752]
FactoryGame_Win64_Shipping!AFGBuildGun::execGotoBuildState() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\public\equipment\fgbuildgun.h:199]
FactoryGame_Win64_Shipping!UFunction::Invoke() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:4644]
FactoryGame_Win64_Shipping!UObject::CallFunction() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:906]
FactoryGame_Win64_Shipping!UObject::ProcessContextOpcode() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:2314]
FactoryGame_Win64_Shipping!ProcessLocalScriptFunction() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:974]
FactoryGame_Win64_Shipping!UObject::ProcessInternal() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1060]
FactoryGame_Win64_Shipping!UFunction::Invoke() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:4644]
FactoryGame_Win64_Shipping!UObject::ProcessEvent() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1464]
FactoryGame_Win64_Shipping!TMulticastScriptDelegate<FWeakObjectPtr>::ProcessMulticastDelegate<UObject>() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\public\uobject\scriptdelegates.h:488]
FactoryGame_Win64_Shipping!FCallDelegateHelper::CallMulticastDelegate() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:2489]
FactoryGame_Win64_Shipping!ProcessLocalScriptFunction() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:974]
FactoryGame_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:809]
FactoryGame_Win64_Shipping!UObject::execLocalFinalFunction() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:2441]
FactoryGame_Win64_Shipping!ProcessLocalScriptFunction() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:974]
FactoryGame_Win64_Shipping!UObject::ProcessInternal() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1060]
FactoryGame_Win64_Shipping!UFunction::Invoke() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\class.cpp:4644]
FactoryGame_Win64_Shipping!UObject::ProcessEvent() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1464]
FactoryGame_Win64_Shipping!TMulticastScriptDelegate<FWeakObjectPtr>::ProcessMulticastDelegate<UObject>() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\public\uobject\scriptdelegates.h:488]
FactoryGame_Win64_Shipping!UButton::SlateHandleClicked() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\umg\private\components\button.cpp:190]
FactoryGame_Win64_Shipping!TBaseUObjectMethodDelegateInstance<0,UAkWwiseTreeSelector,FReply __cdecl(void)>::Execute() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:617]
FactoryGame_Win64_Shipping!SButton::OnMouseButtonUp() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\slate\private\widgets\input\sbutton.cpp:318]
FactoryGame_Win64_Shipping!FEventRouter::Route<FReply,FEventRouter::FToLeafmostPolicy,FPointerEvent,<lambda_73bb70f2c9167b999fc601bc6c844bdb> >() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:271]
FactoryGame_Win64_Shipping!FSlateApplication::RoutePointerUpEvent() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:5598]
FactoryGame_Win64_Shipping!FSlateApplication::ProcessMouseButtonUpEvent() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:6203]
FactoryGame_Win64_Shipping!FSlateApplication::OnMouseUp() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\slate\private\framework\application\slateapplication.cpp:6176]
FactoryGame_Win64_Shipping!FWindowsApplication::ProcessDeferredMessage() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\applicationcore\private\windows\windowsapplication.cpp:1842]
FactoryGame_Win64_Shipping!FWindowsApplication::DeferMessage() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\applicationcore\private\windows\windowsapplication.cpp:2292]
FactoryGame_Win64_Shipping!FWindowsApplication::ProcessMessage() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\applicationcore\private\windows\windowsapplication.cpp:1522]
FactoryGame_Win64_Shipping!FWindowsApplication::AppWndProc() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\applicationcore\private\windows\windowsapplication.cpp:772]
user32
user32
EOSOVH_Win64_Shipping
EOSOVH_Win64_Shipping
user32
user32
FactoryGame_Win64_Shipping!FWindowsPlatformApplicationMisc::PumpMessages() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\applicationcore\private\windows\windowsplatformapplicationmisc.cpp:130]
FactoryGame_Win64_Shipping!FEngineLoop::Tick() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\launchengineloop.cpp:3952]
FactoryGame_Win64_Shipping!GuardedMain() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\launch.cpp:168]
FactoryGame_Win64_Shipping!GuardedMainWrapper() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
FactoryGame_Win64_Shipping!WinMain() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:275]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by mrhid6** [comment]
Fixed please see https://ficsit.app/mod/DGiLzB3ZErWu2V/version/65BSWhrfkstBoz/view
