### ISSUE TITLE
[Crash] Dyson Sphere crash Game

### ISSUE THREAD

**Issue by jrecasens95** [mrhid6/SF_Mod_RefinedPower#24]
Version: 124066, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Epic, NetMode: Listen Server, IsUsingMods: Yes

Assertion failed: Child->IsChildOf(Parent) [File:D:\ws\SB-200518130817-657\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectGlobals.cpp] [Line: 3037] NewObject called with invalid class, SceneComponent must be a child of MeshComponent

**Comment by mrhid6** [comment]
fixed please see this version https://ficsit.app/mod/DGiLzB3ZErWu2V/version/65BSWhrfkstBoz/view
