### ISSUE TITLE
Coal system not producing much power

### ISSUE THREAD

**Issue by Diantane** [mrhid6/SF_Mod_RefinedPower#261]
I've been using Refined Power for over a year -- thank you! This save in U6 (recently released) when I built the coal system, the turbines turn very slowly and often go offline. There is little to no high or low pressure steam. IF I turn off the pipe the steam builds up, but quickly dissipates when it's opened up again. I'm using the Coal Heater, Boiler Mk2. Turbine Mk2 and HV generator. Water tank is full and burning compacted coal. Tried using the earlier systems, they don't work either. Tried putting a heavy demand on the system, but no change.

**Comment by catreplicators** [comment]
Check if the boiler produces enough. It may be a player issue. 
Otherwise, I'll delete this comment

**Comment by Diantane** [comment]
Steam name is "Jeff". Check my profile. To date I have played 2,039 hours (194.4 in last two weeks). Yes I log off when I am done playing. I am a retired tractor trailer driver. 

Boiler is full of water. Using 45 m3/minute. High pressure steam 0/50 in building. Production 60 m3/min. Boiler online. Heater attached. 500 degrees C. Have deleted boiler/pipes and rebuilt (no change). All eight systems have same issue.

https://steamcommunity.com/sharedfiles/filedetails/?id=2872190771

**Comment by Kyri123** [comment]
Is looks like you use mk2 turbines directly connected to a mk2 boiler that have a coal heater right?

that will not work. A boiler mk2 with a coal heater produce 60 steam/min a turbine mk2 use 120/min

**Comment by Diantane** [comment]
I see what you mean. When switching to a Mk1 turbine, the generator starts spinning correctly.
