### ISSUE TITLE
Creating fuel for Micro Reactor full of bugs

### ISSUE THREAD

**Issue by Diantane** [mrhid6/SF_Mod_RefinedPower#267]
Mixed Element 65 with sulfuric acid to make refined element 65 worked fine at first. Then it started piling up in the output of the refiner (by almost 50,000!!). When I tried to make unfiltered deuterium the refined element 65 from the small amount I had in storage wouldn't budge by much. The tank after the refiner said it had 0.001 of unfiltered deuterium in it. Tried using pumps, but they ran dry.

Another issue. When I built the refiners to make the unfiltered deuterium (before bringing in the uranium that was a couple hundred feet away), I had the refined element 65 hooked up to the refinery. As soon as I connected the power, I started getting massive radiation from the refiner. I deleted everything and the radiation went away. Built it all again (again, no uranium), hooked up power and received massive radiation damage again.

**Comment by Kyri123** [comment]
https://github.com/mrhid6/SF_Mod_RefinedPower/issues/277
I think that's the same bug (mod conflict)?

**Comment by bitstormer** [comment]
I am having the same issue with Refined E65.. Hooked up (sulphuric acid and e65) to a refinery and there is no output.

**Comment by bitstormer** [comment]
> I am having the same issue with Refined E65.. Hooked up (sulphuric acid and e65) to a refinery and there is no output.

The OUTPUTS of the refinery are switched.. The refinery is outputting the Refined E65 as a SOLID and not a Liquid!

**Comment by Kyri123** [comment]
Is a mod conflict https://github.com/mrhid6/SF_Mod_RefinedPower/issues/283
