### ISSUE TITLE
SML ERROR

### ISSUE THREAD

**Issue by ichunichu** [mrhid6/SF_Mod_RefinedPower#29]
SML HAS CRASHED: module failed to load D:/satisfactogoidfgdfs/satisfactory/.cach/RefinedPower/UE4-refinedPower-win64-shipping.dll @@@
click OK to exit

Help me to fix my sml error

**Comment by mrhid6** [comment]
@ichunichu what version of refined power have you installed?

**Comment by jinks** [comment]
Refined Power and Farming Mod both have a hard dependency on SML 2.2.0 while 2.2.1 is the current version.

For me just updating the `data.json` worked (so far), but it's a pretty major bug fix...

**Comment by mrhid6** [comment]
Fixed in latest version
