### ISSUE TITLE
Refined e65 recipe wrong

### ISSUE THREAD

**Issue by Polemus** [mrhid6/SF_Mod_RefinedPower#30]
if one look at the docs you provide here and the actual requirements in the refinery, then the recipe is wrong.

On a refinery itself it, to produce 2 cubic meters of refined E65 you need:
- 20 E65
- 2 cubic meters of Sulfuric Acid 

this ratio seems the wrong way around

**Comment by trunkyredstone** [comment]
Which docs are you refering to?

**Comment by Polemus** [comment]
> Which docs are you refering to?

https://github.com/mrhid6/SF_Mod_RefinedPower/tree/master/Info there are some sheets with calculations.

**Comment by mrhid6** [comment]
These spread sheets are for the developers to try out new recipes for balance changes, all stats for recipes should come from with in the game, we are working on getting a wiki up and running to document all the recipes in the mod.
