### ISSUE TITLE
RefinedRDLib, Muliplayer crash when connecting, as Client

### ISSUE THREAD

**Issue by Mlezivan** [mrhid6/SF_Mod_RefinedPower#303]
Version: 202470, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Client, IsUsingMods: Yes

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000

FactoryGame_FactoryGame_Win64_Shipping!UFGSaveSession::OnLevelAddedToWorld() [D:\ws\SB-220602145101-842\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGSaveSession.cpp:467]
FactoryGame_RefinedRDLib_Win64_Shipping!URRDLSubLevelSubsystem::StreamingLevelReceived() [E:\SF\SML\Plugins\RefinedRDLib\Source\RefinedRDLib\Private\RRDLSubLevelSubsystem.cpp:197]
FactoryGame_CoreUObject_Win64_Shipping!UFunction::Invoke() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:5589]
FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1992]
FactoryGame_Engine_Win64_Shipping!FLatentActionManager::TickLatentActionForObject() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Engine\Private\LatentActionManager.cpp:217]
FactoryGame_Engine_Win64_Shipping!FLatentActionManager::ProcessLatentActions() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Engine\Private\LatentActionManager.cpp:145]
FactoryGame_Engine_Win64_Shipping!UWorld::Tick() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Engine\Private\LevelTick.cpp:1526]
FactoryGame_Engine_Win64_Shipping!UGameEngine::Tick() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Engine\Private\GameEngine.cpp:1802]
FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [D:\ws\SB-220602145101-842\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGGameEngine.cpp:16]
FactoryGame_Win64_Shipping!FEngineLoop::Tick() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4896]
FactoryGame_Win64_Shipping!GuardedMain() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Launch\Private\Launch.cpp:169]
FactoryGame_Win64_Shipping!GuardedMainWrapper() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
FactoryGame_Win64_Shipping!WinMain() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by lancce-Wolf** [comment]
same issue here, happens with either ONLY Refined Power (+ Dependencies) installed or ONLY Ficsit Farming (+ Dependencies) installed.
Logs with only refined power installed:
[Client-SMMDebug_2022-10-30_2-22-52.zip](https://github.com/mrhid6/SF_Mod_RefinedPower/files/9894969/Client-SMMDebug_2022-10-30_2-22-52.zip)
[Host-SMMDebug_2022-10-30_2-33-8.zip](https://github.com/mrhid6/SF_Mod_RefinedPower/files/9894970/Host-SMMDebug_2022-10-30_2-33-8.zip)
 i added a comment on #298 which includes the logs with only ficsit farming installed.

**Comment by TerrorBite** [comment]
Confirming this crash occurring with Refined Power installed and Ficsit Farming NOT installed.

Stack trace appears to be identical to the one above.

**Comment by lancce-Wolf** [comment]
recent RefinedRDLib (Version 1.0.11) update seems to have fixed both crash issues with Refined Power and Ficsit Farming.
try again with the Library updated and see if a client can join without crashing.

**Comment by Kyri123** [comment]
I close this issue is fixed now :)

**Comment by Mlezivan** [comment]
Thx, works now
