### ISSUE TITLE
Inventory Spacing

### ISSUE THREAD

**Issue by omegavladd** [mrhid6/SF_Mod_RefinedPower#32]
Few bugs/issues I've noticed while using this mod and I hope they help you improve, as I so far have enjoyed checking it out today.

Original inventory spacing
![image](https://user-images.githubusercontent.com/12886466/89747204-49af0800-da83-11ea-9e31-146512f5b7df.png)

1. Carbon Mesh causing inventory spacing to be adjusted
![image](https://user-images.githubusercontent.com/12886466/89747212-4fa4e900-da83-11ea-9f6e-7960dcc056a6.png)

2. Reinforced Carbon causing inventory spacing to be adjusted
![image](https://user-images.githubusercontent.com/12886466/89747222-54699d00-da83-11ea-9946-02f1111eb59c.png)

3. Reinforced Carbon listed as "Reinforced Carbon Carbon" 
![image](https://user-images.githubusercontent.com/12886466/89747251-8844c280-da83-11ea-8ed6-7259b15ddb1c.png)
![image](https://user-images.githubusercontent.com/12886466/89747190-3a2fbf00-da83-11ea-90ad-4719bc9b2012.png)

**Comment by mrhid6** [comment]
what other mods do you have installed?

**Comment by omegavladd** [comment]
Only mods I have installed are:
Storage Teleporter
Rocket Launcher
Refined Power

**Comment by trunkyredstone** [comment]
Hi there, please join the satisfactory modding discord in order to help you further.

Just ping me - @trunkyredstone#2146 - and i can help you out:
[Here](https://discord.gg/aAayGbe)

**Comment by omegavladd** [comment]
just as an FYI this issue affects more than just myself. There are several posts on various places reporting this issue.
You also said nothing more than "Nice" when I did ping you.
