### ISSUE TITLE
Wind Turbine Area of Effect falls off to 0% with one other in range

### ISSUE THREAD

**Issue by Charixfox** [mrhid6/SF_Mod_RefinedPower#321]
When only one other wind turbine is in the restricted area of another, the power output drops to 0%, not gradually by count as documented.

Reproduction:
1. On the main menu, set to constant wind speed.
2. Build a Wind Turbine Mk 1
3. Connect the Wind Turbine to the power grid to create output
4. Build a second Wind Turbine Mk 1 closer than 32m pitch (center to center) from the first turbine
5. Observe the first turbine output

Expected result:
Output reduced by 33% or other fractional value.

Actual result:
Output reduced to zero

**Comment by Kyri123** [comment]
The documentation is outdated. is not a bug.
