### ISSUE TITLE
Modular UI Source

### ISSUE THREAD

**Issue by recursive-ui** [mrhid6/SF_Mod_RefinedPower#337]
Is it possible to get the modular UI source? Or is there a way to compile without it?

**Comment by Morningstar219** [comment]
i need Modular UI too

**Comment by mrhid6** [comment]
Not sure why you would need the Modular UII source code but you can download the mod from https://ficsit.app/mod/ModularUI

**Comment by recursive-ui** [comment]
Thanks for that I copied the uplugin with the pak files from SMM into the SML project and it now compiles. Sorry I assumed it wouldn't compile without the source.
