### ISSUE TITLE
Missing Widgets from Widget_WindTurbine

### ISSUE THREAD

**Issue by recursive-ui** [mrhid6/SF_Mod_RefinedPower#338]
I loaded the plugin into a fresh install of UE - CSS and the SML project but I am having a weird compile error on one of the widget blueprints. It looks as though for some reason the blueprint is missing all the widgets/design. I did try recopying a fresh version of the uasset from the repo as well but it's the same result. I'm not sure if I have done something very silly here that could have caused it I haven't done any satisfactory modding before but I do know some unreal basics.

![image](https://user-images.githubusercontent.com/122192916/211231888-9403124c-9525-455c-b1f8-4718efacdaff.png)
![image](https://user-images.githubusercontent.com/122192916/211231954-344e04db-835c-4922-b5a0-712f218c252f.png)

**Comment by Kyri123** [comment]
We moved that mod into a private project that source code on GitHub is extremely outdated 

You can’t use that source anymore have a lot of bugs, missing content, missing library’s and wrong code that only works for Update 5. (there are couple of changes since the last commit)
