### ISSUE TITLE
Sphere Dyson Problème

### ISSUE THREAD

**Issue by Taylor31us** [mrhid6/SF_Mod_RefinedPower#381]
Bonjour,
Je fais face à ce que je crois être un bug, jugez plutôt :
 j'ai débloqué au hub les 4 hangars de la sphère de Dyson, j'ai autour de la sphère constitué l'usine capable de la provisionner en temps sur tous les éléments requis.
Je parviens sur chaque étape (avant le compte à rebours de 3m30 à injecter tous les composants (je suis même large de 30 secondes).
Je n'ai donc aucun failed.
La Sphère est bien reliée à l'électricité
Seulement voilà, aucun hangar de n'ouvre et ne passe au vert, le faisceau transperce le ciel mais les hagards demeurent vides, j'ai laissé s'écouler des dizaines et des dizaines d'étapes rien ne se produits, PIRE, lassé, j'ai coupé l'électricité de la sphère pour que ce marasme s'arrête et même sans électricité elle continue ses étapes ..... le bouton pour refresh les failed (qui sont à zero)  ne fonctionne pas même lorsqu'il y en à 1 bref c'est quoi celle blague ?! aidez-moi please.

**Comment by mrhid6** [comment]
Dyson sphere is being discontinued in the next version.
Icarus will be replacing the dyson sphere.
