### ISSUE TITLE
Sound for Icarus Reciever always at max volume

### ISSUE THREAD

**Issue by MaudDibb** [mrhid6/SF_Mod_RefinedPower#383]
The sound for the Icarus reciever, when active, is a bit much. You have to move very far away (probably 10 foundations or more) for it to scale down. in-game volume settings (factory, equipment, even master) have no effect on this. Running latest RP build on latest sf experimental

**Comment by MaudDibb** [comment]
let me ammend the above: modular reactors, turbines, icarus railgun and recievers, all ignore ingame audio settings (even with all settings muted they still play at max volume). The game is literally unplayable near these things because of the deafining roar and sounds coming from all these machines. cant even enjoy my background music playing while near a reactor or icarus reciever, its completely drowned out by the sounds these machines make. please add features to disable these sounds

**Comment by mrhid6** [comment]
Please report all bug reports on the discord server: https://discord.com/channels/729807284103806981/1161678255301070848
