### ISSUE TITLE
Generator does not generate MW

### ISSUE THREAD

**Issue by Tsyklop** [mrhid6/SF_Mod_RefinedPower#56]
I have the following structure:

![Screenshot20200907-11012300000](https://user-images.githubusercontent.com/6783568/92363307-f8357f80-f0f9-11ea-9f3e-a7bcd231661a.png)
![Screenshot20200907-11013300000](https://user-images.githubusercontent.com/6783568/92363310-f966ac80-f0f9-11ea-944b-2cc98d32abbf.png)

And generator does not generate MW:

![Screenshot_1](https://user-images.githubusercontent.com/6783568/92363410-20bd7980-f0fa-11ea-8861-d93adbf99a34.png)

Why?

Mod version 2.1.4

**Comment by winproof** [comment]
hi, same problem, help?

**Comment by Tsyklop** [comment]
@winproof Hi. Set "Steam Discard" to ~3200 in generator. And will work.

**Comment by winproof** [comment]
no luck, i'm affected by bug 55 (slider problem), so i must wait for update 2.1.5, thanks

**Comment by trunkyredstone** [comment]
@winproof , Please set your game language to english. This seems to be the fix until we rework it

**Comment by winproof** [comment]
thanks, i would try :)
