### ISSUE TITLE
Micro reactor consumption rate?

### ISSUE THREAD

**Issue by kspeakman** [mrhid6/SF_Mod_RefinedPower#59]
It is not listed on the building panel or in the mod page.

_Also the Arc Reactor fuel consumption is illegibly small in game._

Amazing mod. I'm just getting into more advanced power with it.

**Comment by trunkyredstone** [comment]
Will be listed on the UI rework soon, and also in the wiki, which is here for now, but will be moved to docs.ficsit.app

**Comment by trunkyredstone** [comment]
Please join our discord for more info: https://discord.gg/UqnVGQ

**Comment by Krzeszny** [comment]
> Will be listed on the UI rework soon, and also in the wiki, which is here for now, but will be moved to docs.ficsit.app

UI hasn't been reworked and wiki doesn't say how quickly it uses reactor cores.
