### ISSUE TITLE
2.1.0 MP Test

### ISSUE THREAD

**Issue by isoindisystems** [mrhid6/SF_Mod_RefinedPower#6]
Hi, how can we test the 2.1.0 mod?
best regards!

**Comment by mrhid6** [comment]
@isoindisystems Hi yea you can test the mod please hit me up on discord and ill send you the mod.

**Comment by isoindisystems** [comment]
awesome!
what´s your username on discord?

**Comment by mrhid6** [comment]
Same as this.. Mrhid6

**Comment by isoindisystems** [comment]
yea, but the 4 digit number...

**Comment by mrhid6** [comment]
Mrhid6#2851
