### ISSUE TITLE
Wind Turbine Mk1 Interface Breaks Game

### ISSUE THREAD

**Issue by CandiceJoy** [mrhid6/SF_Mod_RefinedPower#62]
[Video Showing Issue](https://www.dropbox.com/s/bboppyfn73m5xp8/2020-09-13%2021-06-44.mp4?dl=0)

The video pretty much shows it all, but basically when I open the interface on the wind turbine mk1 and then close it with the X (Escape doesn't seem to work), the interface physically closes but I still have a cursor...I can no longer look around, and no keyboard inputs do anything (aside from alt+f4 obviously).  Version info below (I have it set to Latest).

![image](https://user-images.githubusercontent.com/8854890/93037744-bda37980-f608-11ea-888f-ba8fc69784e4.png)

**Comment by CandiceJoy** [comment]
Update: It's been confirmed that it has to do with clicking the X button in the interface, not closing the interface in general.

**Comment by mrhid6** [comment]
Fixed in 2.1.7
