### ISSUE TITLE
game crashes when attaching/detaching power cable to wind/water turbines

### ISSUE THREAD

**Issue by steeleye11** [mrhid6/SF_Mod_RefinedPower#71]
When I (and a friend in a separate game) attach or detach power lines to/from wind turbines MK1, MK2 and water turbines the game halts/crashes without crash report. Switching back to the previous build version everything is fine again. We are using several mods...
Installed Mods:
Efficiency Checker Mod
Factory Skyline
Ficsit Firearms
Floor Hole and Ceiling Logistics
Fluid Extras
FoundationIndustries
Icon Sign Panel 2.0
Light It Up
Micro Manage
MiniMap
MoarAssets
MoarDevice
MoarFactory
Multi Splitter/Merger Balancer
Ramped Fences
Refined Power
X3-Signs

**Comment by trunkyredstone** [comment]
This is entirely expected,

(Copied from our FAQ over on discord)

**Help! The game is freezing when I do something with refined power!**

If you're on early access, make sure you're using **v2.1.7**, if you're on experimental, then carry on using the latest version (Currently, **v2.1.8**).
You can switch versions in SMM by selecting the Refined Power mod and then pressing the `mod version options` button

**Comment by steeleye11** [comment]
right, we already went back, thanks for the information, we missed that
