### ISSUE TITLE
There is no in-game information regarding consumption or production of modular power buildings

### ISSUE THREAD

**Issue by mkaito** [mrhid6/SF_Mod_RefinedPower#74]
The numbers from the wiki should probably be available somewhere in game.

**Comment by mkaito** [comment]
Here's 10 minutes worth of spreadsheeting btw. tl;dr the ratios are pretty much impossible to work with. But the first table would be nice to have somewhere as a reference. Wiki maybe?


Building Name | Consumes | Produces
-- | -- | --
Biomass Heater | 36 | 48
Coal Heater | 20 | 75
Solution Heater | 14 | 98
Boiler Mk1 | 44 | 72
Boiler Mk2 | 77 | 123
Turbine Mk1 | 25 | 15
Turbine Mk2 | 45 | 22
Steam Chimney | 42 |  
CO2 Chimney | 64 |  


Heater | Heaters | CO2 Chimneys
-- | -- | --
Biomass Heater | 4 | 3
Coal Heater | 64 | 75
Solution Heater | 32 | 49


Boiler | Boilers | Turbine Mk1 | Boilers | Turbine Mk2
-- | -- | -- | -- | --
Boiler Mk1 | 25 | 72 | 5 | 8
Boiler Mk2 | 25 | 123 | 15 | 41


Turbine | Turbines | Chimneys
-- | -- | --
Turbine Mk1 | 14 | 11
Turbine Mk2 | 21 | 11

**Comment by nbrugger-tgm** [comment]
Building Name | Consumes | Produces
-- | -- | --
Solution Heater (Turbo Fuel) | 4.2 | 98

**Comment by mkaito** [comment]
Here's the spreadsheet. It has a little calculator on the side to figure out how many buildings you need to consume a certain amount of fuel.

https://docs.google.com/spreadsheets/d/1V06mbIF9TlukhlONMDRddQKtM-aVNlSVnDxbgQhDv50/edit?usp=sharing

**Comment by parataxus** [comment]
As these numbers seemed a little weird to me I dived into the code to get proper numbers, but could find any. I still have found some useful connections (of course without guarantee): 
- Consumption Rate should be inverse proportional to energy of the consumable (at least within a family) (coal 300MJ, petrol coal 180MJ). Fuel to Turbo Fuel matches this calculation.
- CO2-Production is proportional to energy consumed (within a family)
- the low pressure steam output of a turbine is exactly half of the high pressure input

Yesterday I tested the steady state of burning petrol coal, and a few days ago I made a rough test of coal:
- Petrol Coal was exactly 18 minutes for a stack of 200. This is 2000MJ/min
- Coal steady state seems to be somewhere around 8/min. Calculated from above measurement it would be 6.66/min or 15 minutes per stack of 100. Just from a feeling 20/min for 3 heaters seems about correct.
- the factor from steady to heatup seems to be somewhere between 2.5 and 3. 
- turbines also seem to have a steady state, amount consumed showd 19-21 the most time for mk1 with occasional displays of 15-16
- If I find some more numbers I will update here. I'd love to find the exact numbers in the code, but I fear they are part of assets and not the source code in this repsitory. At least I haven't found them. But on the other hand I'm not familiar with game development.

A side note to efficiency. Calculated for 3 heaters and 8 turbines/generators mk1.
- the input consumption would be 6000MJ/min, that is 100MJ/sec
- the generated power is 1400MW, by definition that is 1400MJ/sec
- a vanilly coal generator creates 75MW while burning 300MJ in 4 seconds
- this means this (relatively easy) setup is 14 times as efficient as vanilla coal generators.
- not tested as not yet reached: heater mk2, turbine mk2 and generator mk3 should produce 4000MW which would make this 40 times as efficient as vanilla coal.
