### ISSUE TITLE
Clarification of the "principle of work" Dyson Sphere

### ISSUE THREAD

**Issue by EldrinnElantey** [mrhid6/SF_Mod_RefinedPower#78]
I would like to clarify the conditional principle of the construction of the Clarification of the "principle of work" [Dyson Sphere](https://en.wikipedia.org/wiki/Dyson_sphere).

Since there are hangars in the design, I can assume that devices are conditionally flying out of it that collect solar energy and send it to the station. If so, then it would be more correct to call it Dyson Swarm.

**Comment by trunkyredstone** [comment]
The hangers are for supply ships that go up and supply the construction that's already up there. The then constructed sphere beams the energy back to the station on the ground.
