### ISSUE TITLE
There is no explanation for the Dyson sphere.

### ISSUE THREAD

**Issue by depalt** [mrhid6/SF_Mod_RefinedPower#8]
I was glad to play the game when I heard that it was updated.
 The Dyson sphere has been updated, but I don't know how to use it.
 Please tell me how to use the Dyson sphere.

**Comment by Luzcile** [comment]
is there a dyson sphere wasnt the dyson sphere removed from this mod didnt find it ingame ?

**Comment by depalt** [comment]
is there a dyson sphere in experimental build.

**Comment by Luzcile** [comment]
uiiii Nice i was really sad bc there wasnt a dyson sphere in early access anymore :D

**Comment by depalt** [comment]
xD
btw, Dyson spheres cost too much material for power production...
 When all the sequences are completed, I wish only a little material needed for the repairs will be included.
its so expensive!! kkkkk

**Comment by Luzcile** [comment]
really what do you mean with expensive ?

**Comment by depalt** [comment]
It meant that the materials were too complex and too many for the production. xD

**Comment by Luzcile** [comment]
Wtf so high cost it couldnt Show them ingame holy shit *-*

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: depalt <notifications@github.com>
Gesendet: Monday, April 27, 2020 10:57:10 AM
An: mrhid6/SF_Mod_RefinedPower <SF_Mod_RefinedPower@noreply.github.com>
Cc: Luzcile <sidoplayer2@hotmail.de>; Comment <comment@noreply.github.com>
Betreff: Re: [mrhid6/SF_Mod_RefinedPower] There is no explanation for the Dyson sphere. (#8)


It meant that the materials were too complex and too many for the production. xD

**Comment by depalt** [comment]
You mean you set it up at a high cost that people can't use yet?

**Comment by depalt** [comment]
oops, I don't know why it is closed xD

**Comment by mrhid6** [comment]
The cost is so high as it produces 1TW of power I don’t really see it being too expensive for unlimited power

**Comment by depalt** [comment]
Yeap you're right. But I think it's easier to build a nuclear power plant than to produce the materials needed for the Dyson sphere.

**Comment by Luzcile** [comment]
ah okey i cant test the dyson sphere in experimentral do i ? i have massive problems with power bc i use 150k mw of power and to produce and transport so much water to power 70 atomic power plants is way to difficult for me bc of the slow pipelines the distance and so on and i think the dyson sphere is awesome bc if i built one of them i have a lot of power :)

**Comment by depalt** [comment]
ummm.. Yeah, I think you're right.
 Thank you for developing this amazing mode! :D
