### ISSUE TITLE
Unable to replace fuel source without replacing solution burner

### ISSUE THREAD

**Issue by theunkn0wn1** [mrhid6/SF_Mod_RefinedPower#89]
In my game, I recently set up turbofuel production, and intended to replace my solution burner power plant's `liquid fuel` supply with `liquid turbofuel`.
Unfortunately, due to what i can only presume is a floating point error, The solution burners refuse to purge their internal fluid buffers and, therefore, refuse to accept any input fuel source other than what they were initially fed.

This is an issue, as cooling the plant off (replacing the burners) is very much suboptimal given how long it takes to warm them back up; it would cause an unacceptable loss in power capacity.

![image](https://user-images.githubusercontent.com/3110986/102705699-2cfbbb80-423f-11eb-87da-7a112c36adda.png)

# Steps to reproduce
1. Fill solution burner with liquid fuel
2. Purge input line and fill line with liquid turbofuel
3. Observe.

# Expected outcome
Solution burner accepts new fuel source without cooling off / needing to be manually replaced

# Actual outcome
Solution burner refuses any input fuel source that isn't what it was initially filled with.

**Comment by mrhid6** [comment]
This is intended, closing
